export const API_DOCS_RPC_CATEGORIES = [
  { key: "blocks", label: "Blocks" },
  { key: "transactions", label: "Transactions" },
  { key: "addresses", label: "Addresses" },
  { key: "tokens", label: "Tokens" },
  { key: "contracts", label: "Contracts" },
  { key: "governance", label: "Governance" },
  { key: "stats", label: "Stats & Traces" },
];

export const API_DOCS_RPC_METHODS = [
  {
    name: "GetBlockCount",
    desc: "Get the latest block height.",
    category: "blocks",
    params: {},
    type: "indexed",
  },
  {
    name: "GetBlockInfoList",
    desc: "Get paginated block summaries.",
    category: "blocks",
    params: { Limit: 20, Skip: 0 },
    type: "indexed",
  },
  {
    name: "GetBlockByBlockHash",
    desc: "Get a block by hash.",
    category: "blocks",
    params: { BlockHash: "0x..." },
    type: "indexed",
  },
  {
    name: "GetTransactionCount",
    desc: "Get total number of indexed transactions.",
    category: "transactions",
    params: {},
    type: "indexed",
  },
  {
    name: "GetTransactionList",
    desc: "Get paginated transaction list.",
    category: "transactions",
    params: { Limit: 20, Skip: 0 },
    type: "indexed",
  },
  {
    name: "GetRawTransactionByTransactionHash",
    desc: "Get transaction detail by tx hash.",
    category: "transactions",
    params: { TransactionHash: "0x..." },
    type: "indexed",
  },
  {
    name: "GetAddressByAddress",
    desc: "Get address summary by wallet address.",
    category: "addresses",
    params: { Address: "N..." },
    type: "indexed",
  },
  {
    name: "GetAssetsHeldByAddress",
    desc: "Get assets currently held by address.",
    category: "addresses",
    params: { Address: "N..." },
    type: "indexed",
  },
  {
    name: "GetNep17TransferByAddress",
    desc: "Get NEP-17 transfer history by address.",
    category: "addresses",
    params: { Address: "N...", Limit: 20, Skip: 0 },
    type: "indexed",
  },
  {
    name: "GetAssetInfos",
    desc: "Get paginated token list.",
    category: "tokens",
    params: { Limit: 20, Skip: 0 },
    type: "indexed",
  },
  {
    name: "GetAssetInfoByContractHash",
    desc: "Get token metadata by contract hash.",
    category: "tokens",
    params: { ContractHash: "0x..." },
    type: "indexed",
  },
  {
    name: "GetAssetHoldersByContractHash",
    desc: "Get top holders for a token contract.",
    category: "tokens",
    params: { ContractHash: "0x...", Limit: 20, Skip: 0 },
    type: "indexed",
  },
  {
    name: "GetContractByContractHash",
    desc: "Get contract detail and manifest.",
    category: "contracts",
    params: { ContractHash: "0x..." },
    type: "indexed",
  },
  {
    name: "GetContractList",
    desc: "Get paginated contract list.",
    category: "contracts",
    params: { Limit: 20, Skip: 0 },
    type: "indexed",
  },
  {
    name: "invokefunction",
    desc: "Native Neo RPC call, forwarded by neo3fura when not handled by indexed API.",
    category: "contracts",
    params: ["0xcontract", "methodName", []],
    type: "passthrough",
  },
  {
    name: "GetCandidate",
    desc: "Get consensus candidates list.",
    category: "governance",
    params: { Limit: 20, Skip: 0 },
    type: "indexed",
  },
  {
    name: "GetCandidateByAddress",
    desc: "Get candidate detail by validator address.",
    category: "governance",
    params: { Address: "N..." },
    type: "indexed",
  },
  {
    name: "GetVotersByCandidateAddress",
    desc: "Get voters for a candidate.",
    category: "governance",
    params: { Address: "N...", Limit: 20, Skip: 0 },
    type: "indexed",
  },
  {
    name: "GetDailyTransactions",
    desc: "Get daily transaction trend.",
    category: "stats",
    params: { Days: 30 },
    type: "indexed",
  },
  {
    name: "GetHourlyTransactions",
    desc: "Get hourly transaction trend.",
    category: "stats",
    params: { Hours: 24 },
    type: "indexed",
  },
  {
    name: "GetNetFeeRange",
    desc: "Get current net fee estimates.",
    category: "stats",
    params: {},
    type: "indexed",
  },
  {
    name: "GetApplicationLogByTransactionHash",
    desc: "Get transaction execution log by tx hash.",
    category: "stats",
    params: { TransactionHash: "0x..." },
    type: "indexed",
  },
  {
    name: "GetExecutionTraceByTransactionHash",
    desc: "Get opcode-level execution trace by tx hash.",
    category: "stats",
    params: { TransactionHash: "0x..." },
    type: "indexed",
  },
];

export const API_DOCS_RPC_PASSTHROUGH_METHODS = new Set(
  API_DOCS_RPC_METHODS.filter((method) => method.type === "passthrough").map((method) => method.name)
);
