import { describe, it, expect, beforeAll } from 'vitest';

const RUN_LIVE_GOVERNANCE_E2E = String(process.env.RUN_LIVE_GOVERNANCE_E2E || "").trim() === "1";
const describeLive = RUN_LIVE_GOVERNANCE_E2E ? describe : describe.skip;

let neon;

describeLive('Governance Tool MultiSig and Signature Collection End-to-End', () => {
  const TESTNET_RPC = "https://testnet1.neo.coz.io:443";
  const TESTNET_WIF = String(process.env.TESTNET_WIF || "").trim();
  
  let account;
  let rpcClient;
  let committeePubkeys;
  let multiSigAccount;
  let unsignedTx;
  let unsignedTxHex;
  let mySignature;
  
  beforeAll(async () => {
    if (!TESTNET_WIF) {
      throw new Error("Missing TESTNET_WIF env var. Refusing to run live governance E2E without an explicit key.");
    }
    const compatModule = await import("../../scripts/lib/loadNeoCompat.js");
    const loadNeoCompat = compatModule.loadNeoCompat || compatModule.default?.loadNeoCompat;
    neon = await loadNeoCompat();
    account = new neon.wallet.Account(TESTNET_WIF);
    rpcClient = new neon.rpc.RPCClient(TESTNET_RPC);
    
    const committee = await rpcClient.getCommittee();
    committeePubkeys = [...committee].sort((a,b) => a.localeCompare(b));
    
    const threshold = Math.floor(committeePubkeys.length / 2) + 1;
    multiSigAccount = neon.wallet.Account.createMultiSig(threshold, committeePubkeys);
  });

  it('Should confirm the user is a valid testnet committee member', () => {
    expect(account.address).toBe('NLtL2v28d7TyMEaXcPqtekunkFRksJ7wxu');
    expect(committeePubkeys.includes(account.publicKey)).toBe(true);
  });

  it('Should generate a valid multi-invocation transaction script', async () => {
    // Mimic the logic from GovernanceTool.vue
    const POLICY_CONTRACT = "0xcc5e4edd9f5f8dba8bb65734541df7a1c081c67b";
    
    const intents = [
      {
        scriptHash: POLICY_CONTRACT,
        operation: "setFeePerByte",
        args: [neon.sc.ContractParam.integer(1000)]
      },
      {
        scriptHash: POLICY_CONTRACT,
        operation: "setExecFeeFactor",
        args: [neon.sc.ContractParam.integer(30)]
      }
    ];

    const script = neon.sc.createScript(...intents);
    expect(script).toBeTruthy();
    expect(script.length).toBeGreaterThan(10);
    
    const currentHeight = await rpcClient.getBlockCount();
    unsignedTx = new neon.tx.Transaction({
      signers: [{ account: multiSigAccount.scriptHash, scopes: neon.tx.WitnessScope.Global }],
      validUntilBlock: currentHeight + 100000,
      systemFee: "100000000",
      networkFee: "500000000",
      script: neon.u.HexString.fromHex(script)
    });

    unsignedTxHex = unsignedTx.serialize(false);
    expect(unsignedTxHex).toBeTruthy();
    expect(unsignedTx.hash()).toBeTruthy();
  });

  it('Should successfully sign the transaction and verify it against the individual pubkey', () => {
    // 1. Sign
    mySignature = neon.wallet.sign(unsignedTxHex, account.privateKey);
    expect(mySignature.length).toBe(128); // 64 bytes hex
    
    // 2. Verify individual signature
    const isValid = neon.wallet.verify(unsignedTxHex, mySignature, account.publicKey);
    expect(isValid).toBe(true);
  });

  it('Should correctly format the multi-signature witness block (Signature Collection Logic)', () => {
    // The UI collects signatures and then broadcasts them.
    // The transaction requires `threshold` signatures. Let's build a mock multi-signature witness
    // to prove that the witness structure generated by the UI logic is acceptable to Neo.
    
    const threshold = Math.floor(committeePubkeys.length / 2) + 1; // 11
    
    // Create an array of mock signatures for the required threshold
    // (We will just use our signature multiple times just to test the witness builder formatting,
    // in reality, each comes from a different pubkey)
    
    // The invocation script for a multisig is just the signatures pushed in order
    const invocationBuilder = new neon.sc.ScriptBuilder();
    
    // To properly build a multisig witness, signatures MUST be ordered identically
    // to how the public keys were sorted in the verification script.
    // Add fake signatures to meet the threshold
    for(let i = 0; i < threshold; i++) {
        invocationBuilder.emitPush(mySignature); 
    }
    
    const invocationScript = invocationBuilder.build();
    
    const witness = new neon.tx.Witness({
      invocationScript: invocationScript,
      verificationScript: neon.u.base642hex(multiSigAccount.contract.script)
    });

    unsignedTx.addWitness(witness);
    
    const signedTxHex = unsignedTx.serialize(true);
    
    expect(witness.verificationScript).toBeTruthy();
    expect(signedTxHex).toBeTruthy();
    expect(signedTxHex.length).toBeGreaterThan(unsignedTxHex.length);
  });
});
