/**
 * NeoVM Opcode Definitions
 * @module utils/neoOpcodes
 * @description Complete NeoVM opcode table for script disassembly
 * @see https://docs.neo.org/docs/en-us/reference/neo_vm.html
 */

// Operand size: how many bytes follow the opcode
// 0 = none, -1 = variable (read from operand prefix), N = fixed N bytes
export const OPCODES = {
  // ── Constants ──
  0x00: { name: "PUSH0", operandSize: 0, desc: "Push empty byte array" },
  0x01: { name: "PUSHINT8", operandSize: 1, desc: "Push 1-byte signed integer" },
  0x02: { name: "PUSHINT16", operandSize: 2, desc: "Push 2-byte signed integer" },
  0x03: { name: "PUSHINT32", operandSize: 4, desc: "Push 4-byte signed integer" },
  0x04: { name: "PUSHINT64", operandSize: 8, desc: "Push 8-byte signed integer" },
  0x05: { name: "PUSHINT128", operandSize: 16, desc: "Push 16-byte signed integer" },
  0x06: { name: "PUSHINT256", operandSize: 32, desc: "Push 32-byte signed integer" },
  0x08: { name: "PUSHT", operandSize: 0, desc: "Push true" },
  0x09: { name: "PUSHF", operandSize: 0, desc: "Push false" },
  0x0a: { name: "PUSHA", operandSize: 4, desc: "Push address (4-byte offset)" },
  0x0b: { name: "PUSHNULL", operandSize: 0, desc: "Push null" },
  0x0c: { name: "PUSHDATA1", operandSize: -1, prefix: 1, desc: "Push data (1-byte length prefix)" },
  0x0d: { name: "PUSHDATA2", operandSize: -1, prefix: 2, desc: "Push data (2-byte length prefix)" },
  0x0e: { name: "PUSHDATA4", operandSize: -1, prefix: 4, desc: "Push data (4-byte length prefix)" },
  0x0f: { name: "PUSHM1", operandSize: 0, desc: "Push -1" },
  0x10: { name: "PUSH0", operandSize: 0, desc: "Push 0" },
  0x11: { name: "PUSH1", operandSize: 0, desc: "Push 1" },
  0x12: { name: "PUSH2", operandSize: 0, desc: "Push 2" },
  0x13: { name: "PUSH3", operandSize: 0, desc: "Push 3" },
  0x14: { name: "PUSH4", operandSize: 0, desc: "Push 4" },
  0x15: { name: "PUSH5", operandSize: 0, desc: "Push 5" },
  0x16: { name: "PUSH6", operandSize: 0, desc: "Push 6" },
  0x17: { name: "PUSH7", operandSize: 0, desc: "Push 7" },
  0x18: { name: "PUSH8", operandSize: 0, desc: "Push 8" },
  0x19: { name: "PUSH9", operandSize: 0, desc: "Push 9" },
  0x1a: { name: "PUSH10", operandSize: 0, desc: "Push 10" },
  0x1b: { name: "PUSH11", operandSize: 0, desc: "Push 11" },
  0x1c: { name: "PUSH12", operandSize: 0, desc: "Push 12" },
  0x1d: { name: "PUSH13", operandSize: 0, desc: "Push 13" },
  0x1e: { name: "PUSH14", operandSize: 0, desc: "Push 14" },
  0x1f: { name: "PUSH15", operandSize: 0, desc: "Push 15" },
  0x20: { name: "PUSH16", operandSize: 0, desc: "Push 16" },

  // ── Flow Control ──
  0x21: { name: "NOP", operandSize: 0, desc: "No operation" },
  0x22: { name: "JMP", operandSize: 1, desc: "Jump (1-byte offset)" },
  0x23: { name: "JMP_L", operandSize: 4, desc: "Jump (4-byte offset)" },
  0x24: { name: "JMPIF", operandSize: 1, desc: "Jump if true" },
  0x25: { name: "JMPIF_L", operandSize: 4, desc: "Jump if true (long)" },
  0x26: { name: "JMPIFNOT", operandSize: 1, desc: "Jump if false" },
  0x27: { name: "JMPIFNOT_L", operandSize: 4, desc: "Jump if false (long)" },
  0x28: { name: "JMPEQ", operandSize: 1, desc: "Jump if equal" },
  0x29: { name: "JMPEQ_L", operandSize: 4, desc: "Jump if equal (long)" },
  0x2a: { name: "JMPNE", operandSize: 1, desc: "Jump if not equal" },
  0x2b: { name: "JMPNE_L", operandSize: 4, desc: "Jump if not equal (long)" },
  0x2c: { name: "JMPGT", operandSize: 1, desc: "Jump if greater" },
  0x2d: { name: "JMPGT_L", operandSize: 4, desc: "Jump if greater (long)" },
  0x2e: { name: "JMPGE", operandSize: 1, desc: "Jump if greater or equal" },
  0x2f: { name: "JMPGE_L", operandSize: 4, desc: "Jump if greater or equal (long)" },
  0x30: { name: "JMPLT", operandSize: 1, desc: "Jump if less" },
  0x31: { name: "JMPLT_L", operandSize: 4, desc: "Jump if less (long)" },
  0x32: { name: "JMPLE", operandSize: 1, desc: "Jump if less or equal" },
  0x33: { name: "JMPLE_L", operandSize: 4, desc: "Jump if less or equal (long)" },
  0x34: { name: "CALL", operandSize: 1, desc: "Call (1-byte offset)" },
  0x35: { name: "CALL_L", operandSize: 4, desc: "Call (4-byte offset)" },
  0x36: { name: "CALLA", operandSize: 0, desc: "Call address on stack" },
  0x37: { name: "CALLT", operandSize: 2, desc: "Call token" },
  0x38: { name: "ABORT", operandSize: 0, desc: "Abort execution" },
  0x39: { name: "ASSERT", operandSize: 0, desc: "Assert top is true" },
  0x3a: { name: "THROW", operandSize: 0, desc: "Throw exception" },
  0x3b: { name: "TRY", operandSize: 2, desc: "Try (catch/finally offsets)" },
  0x3c: { name: "TRY_L", operandSize: 8, desc: "Try long (catch/finally offsets)" },
  0x3d: { name: "ENDTRY", operandSize: 1, desc: "End try" },
  0x3e: { name: "ENDTRY_L", operandSize: 4, desc: "End try (long)" },
  0x3f: { name: "ENDFINALLY", operandSize: 0, desc: "End finally" },
  0x40: { name: "RET", operandSize: 0, desc: "Return" },
  0x41: { name: "SYSCALL", operandSize: 4, desc: "System call (4-byte hash)" },

  // ── Stack Operations ──
  0x43: { name: "DEPTH", operandSize: 0, desc: "Stack depth" },
  0x45: { name: "DROP", operandSize: 0, desc: "Drop top" },
  0x46: { name: "NIP", operandSize: 0, desc: "Remove second item" },
  0x48: { name: "XDROP", operandSize: 0, desc: "Drop N-th item" },
  0x49: { name: "CLEAR", operandSize: 0, desc: "Clear stack" },
  0x4a: { name: "DUP", operandSize: 0, desc: "Duplicate top" },
  0x4b: { name: "OVER", operandSize: 0, desc: "Copy second item to top" },
  0x4d: { name: "PICK", operandSize: 0, desc: "Copy N-th item to top" },
  0x4e: { name: "TUCK", operandSize: 0, desc: "Insert top below second" },
  0x50: { name: "SWAP", operandSize: 0, desc: "Swap top two" },
  0x51: { name: "ROT", operandSize: 0, desc: "Rotate top three" },
  0x52: { name: "ROLL", operandSize: 0, desc: "Move N-th item to top" },
  0x53: { name: "REVERSE3", operandSize: 0, desc: "Reverse top 3" },
  0x54: { name: "REVERSE4", operandSize: 0, desc: "Reverse top 4" },
  0x55: { name: "REVERSEN", operandSize: 0, desc: "Reverse top N" },

  // ── Slot Operations ──
  0x56: { name: "INITSSLOT", operandSize: 1, desc: "Init static slot" },
  0x57: { name: "INITSLOT", operandSize: 2, desc: "Init local+arg slots" },
  0x58: { name: "LDSFLD0", operandSize: 0, desc: "Load static field 0" },
  0x59: { name: "LDSFLD1", operandSize: 0, desc: "Load static field 1" },
  0x5a: { name: "LDSFLD2", operandSize: 0, desc: "Load static field 2" },
  0x5b: { name: "LDSFLD3", operandSize: 0, desc: "Load static field 3" },
  0x5c: { name: "LDSFLD4", operandSize: 0, desc: "Load static field 4" },
  0x5d: { name: "LDSFLD5", operandSize: 0, desc: "Load static field 5" },
  0x5e: { name: "LDSFLD6", operandSize: 0, desc: "Load static field 6" },
  0x5f: { name: "LDSFLD", operandSize: 1, desc: "Load static field N" },
  0x60: { name: "STSFLD0", operandSize: 0, desc: "Store static field 0" },
  0x61: { name: "STSFLD1", operandSize: 0, desc: "Store static field 1" },
  0x62: { name: "STSFLD2", operandSize: 0, desc: "Store static field 2" },
  0x63: { name: "STSFLD3", operandSize: 0, desc: "Store static field 3" },
  0x64: { name: "STSFLD4", operandSize: 0, desc: "Store static field 4" },
  0x65: { name: "STSFLD5", operandSize: 0, desc: "Store static field 5" },
  0x66: { name: "STSFLD6", operandSize: 0, desc: "Store static field 6" },
  0x67: { name: "STSFLD", operandSize: 1, desc: "Store static field N" },
  0x68: { name: "LDLOC0", operandSize: 0, desc: "Load local 0" },
  0x69: { name: "LDLOC1", operandSize: 0, desc: "Load local 1" },
  0x6a: { name: "LDLOC2", operandSize: 0, desc: "Load local 2" },
  0x6b: { name: "LDLOC3", operandSize: 0, desc: "Load local 3" },
  0x6c: { name: "LDLOC4", operandSize: 0, desc: "Load local 4" },
  0x6d: { name: "LDLOC5", operandSize: 0, desc: "Load local 5" },
  0x6e: { name: "LDLOC6", operandSize: 0, desc: "Load local 6" },
  0x6f: { name: "LDLOC", operandSize: 1, desc: "Load local N" },
  0x70: { name: "STLOC0", operandSize: 0, desc: "Store local 0" },
  0x71: { name: "STLOC1", operandSize: 0, desc: "Store local 1" },
  0x72: { name: "STLOC2", operandSize: 0, desc: "Store local 2" },
  0x73: { name: "STLOC3", operandSize: 0, desc: "Store local 3" },
  0x74: { name: "STLOC4", operandSize: 0, desc: "Store local 4" },
  0x75: { name: "STLOC5", operandSize: 0, desc: "Store local 5" },
  0x76: { name: "STLOC6", operandSize: 0, desc: "Store local 6" },
  0x77: { name: "STLOC", operandSize: 1, desc: "Store local N" },
  0x78: { name: "LDARG0", operandSize: 0, desc: "Load argument 0" },
  0x79: { name: "LDARG1", operandSize: 0, desc: "Load argument 1" },
  0x7a: { name: "LDARG2", operandSize: 0, desc: "Load argument 2" },
  0x7b: { name: "LDARG3", operandSize: 0, desc: "Load argument 3" },
  0x7c: { name: "LDARG4", operandSize: 0, desc: "Load argument 4" },
  0x7d: { name: "LDARG5", operandSize: 0, desc: "Load argument 5" },
  0x7e: { name: "LDARG6", operandSize: 0, desc: "Load argument 6" },
  0x7f: { name: "LDARG", operandSize: 1, desc: "Load argument N" },
  0x80: { name: "STARG0", operandSize: 0, desc: "Store argument 0" },
  0x81: { name: "STARG1", operandSize: 0, desc: "Store argument 1" },
  0x82: { name: "STARG2", operandSize: 0, desc: "Store argument 2" },
  0x83: { name: "STARG3", operandSize: 0, desc: "Store argument 3" },
  0x84: { name: "STARG4", operandSize: 0, desc: "Store argument 4" },
  0x85: { name: "STARG5", operandSize: 0, desc: "Store argument 5" },
  0x86: { name: "STARG6", operandSize: 0, desc: "Store argument 6" },
  0x87: { name: "STARG", operandSize: 1, desc: "Store argument N" },

  // ── Splice ──
  0x8b: { name: "NEWBUFFER", operandSize: 0, desc: "Create buffer" },
  0x8c: { name: "MEMCPY", operandSize: 0, desc: "Memory copy" },
  0x8d: { name: "CAT", operandSize: 0, desc: "Concatenate" },
  0x8e: { name: "SUBSTR", operandSize: 0, desc: "Substring" },
  0x8f: { name: "LEFT", operandSize: 0, desc: "Left substring" },
  0x90: { name: "RIGHT", operandSize: 0, desc: "Right substring" },

  // ── Bitwise Logic ──
  0x91: { name: "INVERT", operandSize: 0, desc: "Bitwise NOT" },
  0x92: { name: "AND", operandSize: 0, desc: "Bitwise AND" },
  0x93: { name: "OR", operandSize: 0, desc: "Bitwise OR" },
  0x94: { name: "XOR", operandSize: 0, desc: "Bitwise XOR" },
  0x97: { name: "EQUAL", operandSize: 0, desc: "Equal" },
  0x98: { name: "NOTEQUAL", operandSize: 0, desc: "Not equal" },

  // ── Arithmetic ──
  0x99: { name: "SIGN", operandSize: 0, desc: "Sign of top" },
  0x9a: { name: "ABS", operandSize: 0, desc: "Absolute value" },
  0x9b: { name: "NEGATE", operandSize: 0, desc: "Negate" },
  0x9c: { name: "INC", operandSize: 0, desc: "Increment" },
  0x9d: { name: "DEC", operandSize: 0, desc: "Decrement" },
  0x9e: { name: "ADD", operandSize: 0, desc: "Add" },
  0x9f: { name: "SUB", operandSize: 0, desc: "Subtract" },
  0xa0: { name: "MUL", operandSize: 0, desc: "Multiply" },
  0xa1: { name: "DIV", operandSize: 0, desc: "Divide" },
  0xa2: { name: "MOD", operandSize: 0, desc: "Modulo" },
  0xa3: { name: "POW", operandSize: 0, desc: "Power" },
  0xa4: { name: "SQRT", operandSize: 0, desc: "Square root" },
  0xa8: { name: "SHL", operandSize: 0, desc: "Shift left" },
  0xa9: { name: "SHR", operandSize: 0, desc: "Shift right" },
  0xaa: { name: "NOT", operandSize: 0, desc: "Logical NOT" },
  0xab: { name: "BOOLAND", operandSize: 0, desc: "Logical AND" },
  0xac: { name: "BOOLOR", operandSize: 0, desc: "Logical OR" },
  0xb1: { name: "NZ", operandSize: 0, desc: "Not zero" },
  0xb3: { name: "NUMEQUAL", operandSize: 0, desc: "Numeric equal" },
  0xb4: { name: "NUMNOTEQUAL", operandSize: 0, desc: "Numeric not equal" },
  0xb5: { name: "LT", operandSize: 0, desc: "Less than" },
  0xb6: { name: "LE", operandSize: 0, desc: "Less or equal" },
  0xb7: { name: "GT", operandSize: 0, desc: "Greater than" },
  0xb8: { name: "GE", operandSize: 0, desc: "Greater or equal" },
  0xb9: { name: "MIN", operandSize: 0, desc: "Minimum" },
  0xba: { name: "MAX", operandSize: 0, desc: "Maximum" },
  0xbb: { name: "WITHIN", operandSize: 0, desc: "Within range" },

  // ── Compound Types ──
  0xc0: { name: "PACK", operandSize: 0, desc: "Pack into array" },
  0xc1: { name: "UNPACK", operandSize: 0, desc: "Unpack array" },
  0xc2: { name: "NEWARRAY0", operandSize: 0, desc: "New empty array" },
  0xc3: { name: "NEWARRAY", operandSize: 0, desc: "New array of size N" },
  0xc4: { name: "NEWARRAY_T", operandSize: 1, desc: "New typed array" },
  0xc5: { name: "NEWSTRUCT0", operandSize: 0, desc: "New empty struct" },
  0xc6: { name: "NEWSTRUCT", operandSize: 0, desc: "New struct of size N" },
  0xc8: { name: "NEWMAP", operandSize: 0, desc: "New map" },
  0xca: { name: "SIZE", operandSize: 0, desc: "Get size" },
  0xcb: { name: "HASKEY", operandSize: 0, desc: "Has key" },
  0xcc: { name: "KEYS", operandSize: 0, desc: "Get keys" },
  0xcd: { name: "VALUES", operandSize: 0, desc: "Get values" },
  0xce: { name: "PICKITEM", operandSize: 0, desc: "Pick item by key" },
  0xcf: { name: "APPEND", operandSize: 0, desc: "Append to array" },
  0xd0: { name: "SETITEM", operandSize: 0, desc: "Set item by key" },
  0xd1: { name: "REVERSEITEMS", operandSize: 0, desc: "Reverse items" },
  0xd2: { name: "REMOVE", operandSize: 0, desc: "Remove item" },
  0xd3: { name: "CLEARITEMS", operandSize: 0, desc: "Clear all items" },
  0xd4: { name: "POPITEM", operandSize: 0, desc: "Pop last item" },

  // ── Type Operations ──
  0xd8: { name: "ISNULL", operandSize: 0, desc: "Is null" },
  0xd9: { name: "ISTYPE", operandSize: 1, desc: "Is type" },
  0xdb: { name: "CONVERT", operandSize: 1, desc: "Convert type" },
  0xdc: { name: "ABORTMSG", operandSize: 0, desc: "Abort with message" },
  0xdd: { name: "ASSERTMSG", operandSize: 0, desc: "Assert with message" },
};

/**
 * Well-known NeoVM SYSCALL hashes (4-byte little-endian FNV-1a of the name).
 * Used to resolve SYSCALL operands to human-readable names.
 */
export const SYSCALL_HASHES = {
  "9bf667ce": "System.Contract.Call",
  "627d5b52": "System.Contract.CallNative",
  "3ab29bac": "System.Contract.CreateStandardAccount",
  ceb35ed3: "System.Contract.CreateMultisigAccount",
  e63f1884: "System.Contract.GetCallFlags",
  "925de831": "System.Contract.NativeOnPersist",
  dae24b21: "System.Contract.NativePostPersist",
  f827ec8c: "System.Runtime.Platform",
  b7c38bfa: "System.Runtime.GetTrigger",
  ea1a60ca: "System.Runtime.GetTime",
  de97a4b5: "System.Runtime.GetScriptContainer",
  "2d510830": "System.Runtime.GetExecutingScriptHash",
  a55c1a3a: "System.Runtime.GetCallingScriptHash",
  b3b7e3c1: "System.Runtime.GetEntryScriptHash",
  f4519eca: "System.Runtime.CheckWitness",
  "95016f61": "System.Runtime.GetInvocationCounter",
  "274335f1": "System.Runtime.GetRandom",
  "7f4440a3": "System.Runtime.Log",
  "95f82f09": "System.Runtime.Notify",
  b3a6e3a6: "System.Runtime.GetNotifications",
  "521a0e6a": "System.Runtime.GasLeft",
  "1209ade2": "System.Runtime.BurnGas",
  "4d510877": "System.Runtime.GetNetwork",
  "7ecc7b2a": "System.Runtime.GetAddressVersion",
  "3b7346ea": "System.Runtime.CurrentSigners",
  "9a4c145e": "System.Runtime.LoadScript",
  "3e01e1e5": "System.Crypto.CheckSig",
  "987b5a40": "System.Crypto.CheckMultisig",
  "925b3c6a": "System.Iterator.Next",
  e6332394: "System.Iterator.Value",
  dc67d9ba: "System.Storage.GetContext",
  "793e7eea": "System.Storage.GetReadOnlyContext",
  "632688d4": "System.Storage.AsReadOnly",
  "03e81039": "System.Storage.Get",
  fb5015a8: "System.Storage.Find",
  e4a0b5b4: "System.Storage.Put",
  "5765696d": "System.Storage.Delete",
};
