-- Schema-as-code for the existing live network_alerts table.
--
-- This table already exists in production (created ad hoc, outside of any
-- migration), so until now fresh environments and reviewers had no
-- source-of-truth for its shape. This migration codifies it with
-- create-if-not-exists semantics: applying it against the live database is a
-- no-op and therefore safe; applying it to a fresh database produces the
-- shape the api/ code depends on.
--
-- Every column below is derived from the read/write sites in api/:
--   api/network_alerts.js  insert { network, alert_type, threshold, target,
--                          contact, is_active: true, miss_count: 0,
--                          last_seen_state: "" } and select the generated id
--                          back (insert(..).select("id").single())
--   api/check_alerts.js    select * where network = .. and is_active = true;
--                          update { last_seen_state, miss_count, is_active }
--                          where id = ..
--
-- Semantics per column (from api/network_alerts.js normalizeAlertPayload and
-- api/check_alerts.js):
--   alert_type       one of consensus_stuck | consensus_missed | account_event
--   threshold        seconds for consensus_stuck (30/60/120/300), miss-streak
--                    count for consensus_missed; null otherwise
--   target           consensus public key or account address; null for
--                    consensus_stuck
--   contact          alert delivery email
--   last_seen_state  block height (as text) for consensus_missed, last seen
--                    tx hash for account_event
create table if not exists network_alerts (
  id              bigint  generated by default as identity primary key,
  network         text    not null,
  alert_type      text    not null,
  threshold       integer,
  target          text,
  contact         text    not null,
  is_active       boolean not null default true,
  miss_count      integer not null default 0,
  last_seen_state text    not null default ''
);
