import { describe, expect, it } from "vitest";

import {
  buildHandlerCoverageSet,
  buildDocStub,
  collectApiDocsCatalogIssues,
  collectApiDocsCatalogUsageIssues,
  extractMethodArgsFromApiSource,
  findMissingMethods,
  isAutogeneratedDocContent,
  isReservedDocContent,
  methodToDocFileName,
} from "../../scripts/validate-rpc-consistency.mjs";

describe("validate-rpc-consistency helpers", () => {
  it("maps method names to canonical doc filenames", () => {
    expect(methodToDocFileName("GetExecutionTraceByTransactionHash")).toBe(
      "getExecutionTraceByTransactionHash.md"
    );
    expect(methodToDocFileName("getblock")).toBe("getblock.md");
  });

  it("extracts typed args from Go API handler source", () => {
    const source = `
func (me *T) GetBidInfoByNFT(args struct {
  Address    h160.T
  AssetHash  h160.T
  TokenId    strval.T
  Limit      int64
  Filter     map[string]interface{}
}, ret *json.RawMessage) error {
  return nil
}
`;

    expect(extractMethodArgsFromApiSource(source, "GetBidInfoByNFT")).toEqual([
      { name: "Address", type: "h160.T" },
      { name: "AssetHash", type: "h160.T" },
      { name: "TokenId", type: "strval.T" },
      { name: "Limit", type: "int64" },
      { name: "Filter", type: "map[string]interface{}" },
    ]);
  });

  it("builds a markdown stub including method and parameters", () => {
    const content = buildDocStub({
      method: "GetBidInfoByNFT",
      params: [
        { name: "AssetHash", type: "h160.T" },
        { name: "Filter", type: "map[string]interface{}" },
        { name: "TokenId", type: "strval.T" },
      ],
    });

    expect(content).toContain("# GetBidInfoByNFT");
    expect(content).toContain('"method": "GetBidInfoByNFT"');
    expect(content).toContain("| AssetHash | h160.T | TODO | Optional |");
    expect(content).toContain("| Filter | map[string]interface{} | TODO | Optional |");
    expect(content).toContain("| TokenId | strval.T | TODO | Optional |");
    expect(content).toContain('"Filter": {}');
  });

  it("detects autogenerated doc placeholders", () => {
    expect(
      isAutogeneratedDocContent("Auto-generated API documentation stub. Replace TODO placeholders.")
    ).toBe(true);
    expect(isAutogeneratedDocContent("# GetBlockCount\nHuman-written documentation.")).toBe(false);
  });

  it("detects reserved compatibility docs", () => {
    expect(
      isReservedDocContent(
        "# GetFoo\nLegacy allowlisted API name reserved for compatibility. This method is not implemented."
      )
    ).toBe(true);
    expect(isReservedDocContent("# GetBlockCount\nHuman-written documentation.")).toBe(false);
  });

  it("finds missing methods while honoring exemptions", () => {
    const missing = findMissingMethods({
      requiredMethods: ["GetBlockCount", "invokefunction", "GetMissing"],
      availableMethods: new Set(["GetBlockCount"]),
      exemptMethods: new Set(["invokefunction"]),
    });

    expect(missing).toEqual(["GetMissing"]);
  });

  it("builds handler coverage including lower-first aliases", () => {
    const coverage = buildHandlerCoverageSet(new Set(["GetBlockCount", "Getblock"]));
    expect(coverage.has("GetBlockCount")).toBe(true);
    expect(coverage.has("getBlockCount")).toBe(true);
    expect(coverage.has("Getblock")).toBe(true);
    expect(coverage.has("getblock")).toBe(true);
  });

  it("collects api docs catalog structural issues", () => {
    const issues = collectApiDocsCatalogIssues({
      categories: [{ key: "blocks" }, { key: "blocks" }],
      methods: [
        { name: "GetBlockCount", category: "blocks", type: "indexed" },
        { name: "GetBlockCount", category: "unknown", type: "passthrough" },
        { name: "invokefunction", category: "blocks", type: "indexed" },
      ],
      passthroughMethods: new Set(["invokefunction"]),
    });

    expect(issues.duplicateCategoryKeys).toEqual(["blocks"]);
    expect(issues.duplicateMethodNames).toEqual(["GetBlockCount"]);
    expect(issues.methodsWithUnknownCategory).toEqual(["GetBlockCount"]);
    expect(issues.passthroughMethodTypeMismatches).toEqual(["invokefunction"]);
    expect(issues.passthroughTypeMissingFromSet).toEqual(["GetBlockCount"]);
  });

  it("collects api docs catalog usage drift issues", () => {
    const issues = collectApiDocsCatalogUsageIssues({
      catalogMethodNames: ["GetBlockCount", "GetBlockInfoList"],
      frontendMethodNames: new Set(["GetBlockCount"]),
    });

    expect(issues.catalogMethodsMissingInFrontendUsage).toEqual(["GetBlockInfoList"]);
  });
});
